### PR TITLE
Fix the events service connection

### LINKED ISSUE #255: [Mainnet Issue] - Fix the events service connection

### PR DESCRIPTION
**Pull request by dailinsubjam**
Closes #255 

Pasted here what @Ayiga mentioned regarding the connection issue:
- I noticed during the running of the inscriptions service, after Mainnet went through it’s degraded behavior and recovered, that the Block stream never recovered.
    - There’s already code in both the Builder and in the Inscriptions service to automatically reconnect when we detect that the stream is “closed”.  There may be some underlying issue with the source rather than the consumer.
    - We may still want to address this on the consumer side, however, and the best way to address that, I think, is to keep track of the time since the last object received.
    - Since both the Block Stream, and the Event Stream should be receiving events fairly often, it seems like a good safe guard to determine whether we are in a state that doesn’t seem to be progressing.
    - Once this state is detected, we can just trigger a reconnect in hopes that it will recover and resolve the issue.
    
    > NOTE: With this approach, we may end up triggering (at least with the block stream) unnecessarily due to potential latency / timeouts in the consensus protocol itself.

### This PR:
- Adds a time period check for disconnecting and reconnecting when no events are received for too long ( now set to 1 second).
- Introduces a timestamp to track the last received event time in EventServiceStream.

### CODE REVIEW

File: crates/shared/src/utils.rs [hunk 1]
```diff
@@ -156,40 +157,50 @@ impl<Types: NodeType, ApiVer: StaticVersionType + 'static> EventServiceStream<Ty
...
                             error!(?err, "Error while reconnecting, will retry in a while");
                             sleep(Self::RETRY_PERIOD).await;
                             let fut = Self::connect_inner(this.api_url.clone());
                             let _ = std::mem::replace(&mut this.connection, Right(Box::pin(fut)));
-                            continue;
                         }
                     },
                 }
+
+                // Disconnect and reconnect if no event has been received within quite a long time (set to 1s by default)
```
Comment (QuentinI) [inline crates/shared/src/utils.rs:198]: This code will be executed _after_ we received the event, so what we'll detect here is a long period without events that _has just ended_. What we should do instead is set a timeout on connection.next() and handle timeout

File: crates/shared/src/utils.rs [hunk 2]
```diff
@@ -323,6 +343,46 @@ mod tests {
...
+
+        // The stream should work when the server is running
+        timeout(TIMEOUT, stream.next())
+            .await
+            .expect("When mock event server is spawned, stream should work")
+            .unwrap();
+
+        // Simulate idle timeout by stopping the server and waiting
+        app_handle.abort();
+        tokio::time::sleep(IDLE_TIMEOUT + Duration::from_millis(500)).await; // Wait longer than idle timeout
```
Comment (shenkeyao) [inline crates/shared/src/utils.rs:373]: Why can't this just be `IDLE_TIMEOUT`? Or can we increase `IDLE_TIMEOUT` to 2 seconds if we want it to be longer?

File: crates/shared/src/utils.rs [hunk 3]
```diff
@@ -323,6 +343,46 @@ mod tests {
             .await
             .expect_err("API is reachable, but is on wrong path");
     }
+
+    #[tokio::test(flavor = "multi_thread")]
+    async fn event_stream_wrapper_with_idle_timeout() {
```
Comment (shenkeyao) [inline crates/shared/src/utils.rs:348]: Nit: Can we add `test_` to the test name to distinguish it from test helpers? Would be nice to rename other tests in this file as well if not too much additional work!

File: crates/shared/src/utils.rs (hunk 2 above)
Comment (shenkeyao) [reply crates/shared/src/utils.rs:373]: If these consts are tied (maybe not?) with the setting in non-test code, e.g., the `connect` function, can we move them to the non-test module near `RETRY_PERIOD` and replace hard-coded values with them?

File: crates/shared/src/utils.rs [hunk 4]
```diff
@@ -109,6 +109,7 @@ type EventServiceReconnect<Types, ApiVer> = Pin<
 pub struct EventServiceStream<Types: NodeType, V: StaticVersionType> {
     api_url: Url,
     connection: Either<EventServiceConnection<Types, V>, EventServiceReconnect<Types, V>>,
+    last_event_time: Instant, // a field to track the time of the last received event
```
Comment (shenkeyao) [inline crates/shared/src/utils.rs:112]: Is this ever used?

File: crates/shared/src/utils.rs (hunk 2 above)
Comment (dailinsubjam) [reply crates/shared/src/utils.rs]: 500ms is to make sure we wait at least IDLE_TIMEOUT. It's also fine to do a smaller add-on. Updated to `RETRY_PERIOD` in [2a9d3ab](https://github.com/EspressoSystems/marketplace-builder-core/pull/257/commits/2a9d3ab17e82a1bd38b3918a53523b095aee626b).

File: crates/shared/src/utils.rs (hunk 3 above)
Comment (dailinsubjam) [reply crates/shared/src/utils.rs]: [9561de9](https://github.com/EspressoSystems/marketplace-builder-core/pull/257/commits/9561de982902417d0821767bf71988c8e0a7e324).

File: crates/shared/src/utils.rs (hunk 2 above)
Comment (shenkeyao) [reply crates/shared/src/utils.rs]: I'm still confused about the purpose of setting the `sleep` period at least `RETRY_PERIOD` if we create a new app immediately afterward.

IIUC when the period exceeds `RETRY_PERIOD`, the `connection.next()` call will enter the `Err(_)` case, whereas before this PR, it would get stuck. However, if we create a `new_app_handle` immediately after this `sleep` period, it looks like we are essentially testing what's already covered in `test_event_stream_wrapper`.

I think we should verify whether `.next()` returns an error as expected after the `sleep`, i.e., whether we do try to reconnect.

**Review by shenkeyao — COMMENTED** [review]
As replied to a previous discussion, I think the test needs additional assertion to make sure the reconnection works.

**Review by shenkeyao — APPROVED** [review]
